[build]
  command = "cd .. && pnpm install && pnpm run build:landing"
  publish = ".next"
  base = "trueflow-landing"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/app"
  to = "https://app.trueflow.ai"
  status = 301
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://app.trueflow.ai/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"