# Nixpacks configuration for TrueFlow Landing Page

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "PORT=${PORT:-3001} npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Cache configuration
[cache]
paths = [
  "node_modules",
  ".next/cache"
]