# Nixpacks configuration for TrueFlow Landing Page

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm cache clean --force",
  "rm -rf node_modules .next",
  "npm install --force"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"