# Nixpacks configuration for TrueFlow Landing Page

[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "pnpm run build"
]

[start]
cmd = "PORT=${PORT:-3001} pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Cache configuration
[cache]
paths = [
  "node_modules",
  ".pnpm-store",
  ".next/cache"
]